/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running app. It is committed here so
// TypeScript understands Next-specific types before the first local dev run.
